apiVersion: v1
kind: ConfigMap
metadata:
  name: dex
data:
  config.yaml: |
    issuer: http://dex.auth.svc.cluster.local:5556/dex
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:5556
    logger:
      level: "debug"
      format: text
    oauth2:
      skipApprovalScreen: true
    enablePasswordDB: true
    staticPasswords:
    - email: seva.kabrits@gmail.com
      hashFromEnv: DEX_USER_PASSWORD
      username: seva.kabrits
      userID: "15841185641784"
    - email: fake@gmail.com
      hash: $2y$12$iCXmTIvNMov9DLh2WFkpNeT2QH6UPsjVFJk4OYfBzU080Ig2YjYbi
      username: fake
      userID: "15841185641785"
    - email: fake1@gmail.com
      hash: $2y$12$iCXmTIvNMov9DLh2WFkpNeT2QH6UPsjVFJk4OYfBzU080Ig2YjYbi
      username: fake1
      userID: "15841185641786"
    staticClients:
    # https://github.com/dexidp/dex/pull/1664
    - idEnv: OIDC_CLIENT_ID
      redirectURIs: ["/oauth2/callback"]
      name: 'Dex Login Application'
      secretEnv: OIDC_CLIENT_SECRET
